### PR TITLE
Add callbacks for onFocus and onBlur

### PR DESCRIPTION
**Pull request by slwen**
Maybe there is another way to do this but I personally ran in to situations where I wanted to move elements in my prototype based on whether the keyboard was visible or not.

Adding some simple callback options for the `focus` and `blur` events helped me to achieve that fairly easily. Open to a different approach if you have something in mind @ajimix

### CODE REVIEW

**Comment by ajimix** [comment]
Hey @slwen doesn't this work for you? I can't try right now but it should work

```
input.on "focus", ->
    print @value
```

**Comment by slwen** [comment]
Hey @ajimix that was also my first instinct, unfortunately it didn't work for me.

**Comment by ajimix** [comment]
Ok, Iḿ now out of my country and office until the 16th, let me do a quick check once I'm back and if I don see why is not working I'll merge this request.
Thanks for your contribution :)

**Comment by curly-brackets** [comment]
It's working for me.

**Comment by slwen** [comment]
In case I'm crazy, here's an example of the code I'm using:

``` js
searchFieldInput = new InputModule.Input
    placeholder: 'Search for an opponent...'
    x: 110
    y: 161
    height: 74
    width: 600

searchFieldInput.on "focus", ->
    print 'im focused'
```

On focusing the input nothing is printed for me.

**Comment by curly-brackets** [comment]
Hi - you aint crazy. Maybe just distracted?

“focus” doesn’t work. “keyup” works.

InputModule = require "input"

searchFieldInput = new InputModule.Input
    placeholder: 'Search for an opponent...'
    x: 110
    y: 161
    height: 74
    width: 600

searchFieldInput.on "keyup", ->
    print 'im focused'

**Comment by slwen** [comment]
@curly-brackets that's not quite what I'm after. The `keyup` event triggers only during entering input. The effect I am after is to trigger animations alongside the same `focus` event that the keyboard listens for, here's an example of what I'm doing in action:

keyboard480

Notice the small circular avatar images in the bottom right and how they move up and down in reaction to the keyboard.

**Comment by ajimix** [comment]
@slwen I'm back and I could dedicate some time on this issue.
As you say, what I suggested is not working. I saw your PR but I preferred to follow the approach that Framer users for the Layer object.

Here you can see what I did: https://github.com/ajimix/Input-Framer/commit/565503f686a35852736315096b86add453a2c805

So now you can do:

``` coffeescript
input.onFocus ->
    print "Input is focused and has the value: #{@value}" 

input.onBlur ->
    print "Input is out of focus and this is the value: #{@value}"
```

Here you can see a working example: http://share.framerjs.com/tt4cayq1qmsz/

Thanks for your work and collaboration. Now I'm closing this pull request 👍

**Pull request closed without merging**
